version: "2"
run:
  build-tags:
    - integration
linters:
  enable:
    - gosec
    - misspell
    - revive
  settings:
    gosec:
      excludes:
        - G404
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
