// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: netboot/v1/artifact.proto

package netbootv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationArtifactServiceDeleteArtifact = "/netboot.v1.ArtifactService/DeleteArtifact"
const OperationArtifactServiceGetArtifact = "/netboot.v1.ArtifactService/GetArtifact"
const OperationArtifactServiceListArtifacts = "/netboot.v1.ArtifactService/ListArtifacts"
const OperationArtifactServiceListTransfers = "/netboot.v1.ArtifactService/ListTransfers"

type ArtifactServiceHTTPServer interface {
	DeleteArtifact(context.Context, *GetArtifactRequest) (*emptypb.Empty, error)
	GetArtifact(context.Context, *GetArtifactRequest) (*BootArtifact, error)
	ListArtifacts(context.Context, *PageRequest) (*ListArtifactsReply, error)
	ListTransfers(context.Context, *ListTransfersRequest) (*ListTransfersReply, error)
}

func RegisterArtifactServiceHTTPServer(s *http.Server, srv ArtifactServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/artifacts", _ArtifactService_ListArtifacts0_HTTP_Handler(srv))
	r.GET("/api/v1/artifacts/{id}", _ArtifactService_GetArtifact0_HTTP_Handler(srv))
	r.DELETE("/api/v1/artifacts/{id}", _ArtifactService_DeleteArtifact0_HTTP_Handler(srv))
	r.GET("/api/v1/artifacts/transfers", _ArtifactService_ListTransfers0_HTTP_Handler(srv))
}

func _ArtifactService_ListArtifacts0_HTTP_Handler(srv ArtifactServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PageRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArtifactServiceListArtifacts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListArtifacts(ctx, req.(*PageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListArtifactsReply)
		return ctx.Result(200, reply)
	}
}

func _ArtifactService_GetArtifact0_HTTP_Handler(srv ArtifactServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetArtifactRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArtifactServiceGetArtifact)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetArtifact(ctx, req.(*GetArtifactRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BootArtifact)
		return ctx.Result(200, reply)
	}
}

func _ArtifactService_DeleteArtifact0_HTTP_Handler(srv ArtifactServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetArtifactRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArtifactServiceDeleteArtifact)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteArtifact(ctx, req.(*GetArtifactRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ArtifactService_ListTransfers0_HTTP_Handler(srv ArtifactServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTransfersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArtifactServiceListTransfers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTransfers(ctx, req.(*ListTransfersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTransfersReply)
		return ctx.Result(200, reply)
	}
}

type ArtifactServiceHTTPClient interface {
	DeleteArtifact(ctx context.Context, req *GetArtifactRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetArtifact(ctx context.Context, req *GetArtifactRequest, opts ...http.CallOption) (rsp *BootArtifact, err error)
	ListArtifacts(ctx context.Context, req *PageRequest, opts ...http.CallOption) (rsp *ListArtifactsReply, err error)
	ListTransfers(ctx context.Context, req *ListTransfersRequest, opts ...http.CallOption) (rsp *ListTransfersReply, err error)
}

type ArtifactServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewArtifactServiceHTTPClient(client *http.Client) ArtifactServiceHTTPClient {
	return &ArtifactServiceHTTPClientImpl{client}
}

func (c *ArtifactServiceHTTPClientImpl) DeleteArtifact(ctx context.Context, in *GetArtifactRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/artifacts/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArtifactServiceDeleteArtifact))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ArtifactServiceHTTPClientImpl) GetArtifact(ctx context.Context, in *GetArtifactRequest, opts ...http.CallOption) (*BootArtifact, error) {
	var out BootArtifact
	pattern := "/api/v1/artifacts/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArtifactServiceGetArtifact))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ArtifactServiceHTTPClientImpl) ListArtifacts(ctx context.Context, in *PageRequest, opts ...http.CallOption) (*ListArtifactsReply, error) {
	var out ListArtifactsReply
	pattern := "/api/v1/artifacts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArtifactServiceListArtifacts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ArtifactServiceHTTPClientImpl) ListTransfers(ctx context.Context, in *ListTransfersRequest, opts ...http.CallOption) (*ListTransfersReply, error) {
	var out ListTransfersReply
	pattern := "/api/v1/artifacts/transfers"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArtifactServiceListTransfers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
