// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: netboot/v1/dhcp.proto

package netbootv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDhcpServiceDisableDhcp = "/netboot.v1.DhcpService/DisableDhcp"
const OperationDhcpServiceEnableDhcp = "/netboot.v1.DhcpService/EnableDhcp"
const OperationDhcpServiceGetDhcpConfig = "/netboot.v1.DhcpService/GetDhcpConfig"
const OperationDhcpServiceListForeignServers = "/netboot.v1.DhcpService/ListForeignServers"
const OperationDhcpServiceListLeases = "/netboot.v1.DhcpService/ListLeases"
const OperationDhcpServiceUpdateDhcpConfig = "/netboot.v1.DhcpService/UpdateDhcpConfig"

type DhcpServiceHTTPServer interface {
	DisableDhcp(context.Context, *emptypb.Empty) (*DhcpConfig, error)
	EnableDhcp(context.Context, *emptypb.Empty) (*DhcpConfig, error)
	GetDhcpConfig(context.Context, *emptypb.Empty) (*DhcpConfig, error)
	ListForeignServers(context.Context, *PageRequest) (*ListForeignServersReply, error)
	ListLeases(context.Context, *PageRequest) (*ListLeasesReply, error)
	UpdateDhcpConfig(context.Context, *UpdateDhcpConfigRequest) (*DhcpConfig, error)
}

func RegisterDhcpServiceHTTPServer(s *http.Server, srv DhcpServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/dhcp/config", _DhcpService_GetDhcpConfig0_HTTP_Handler(srv))
	r.PUT("/api/v1/dhcp/config", _DhcpService_UpdateDhcpConfig0_HTTP_Handler(srv))
	r.POST("/api/v1/dhcp/enable", _DhcpService_EnableDhcp0_HTTP_Handler(srv))
	r.POST("/api/v1/dhcp/disable", _DhcpService_DisableDhcp0_HTTP_Handler(srv))
	r.GET("/api/v1/dhcp/leases", _DhcpService_ListLeases0_HTTP_Handler(srv))
	r.GET("/api/v1/dhcp/conflicts", _DhcpService_ListForeignServers0_HTTP_Handler(srv))
}

func _DhcpService_GetDhcpConfig0_HTTP_Handler(srv DhcpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDhcpServiceGetDhcpConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDhcpConfig(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DhcpConfig)
		return ctx.Result(200, reply)
	}
}

func _DhcpService_UpdateDhcpConfig0_HTTP_Handler(srv DhcpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateDhcpConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDhcpServiceUpdateDhcpConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateDhcpConfig(ctx, req.(*UpdateDhcpConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DhcpConfig)
		return ctx.Result(200, reply)
	}
}

func _DhcpService_EnableDhcp0_HTTP_Handler(srv DhcpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDhcpServiceEnableDhcp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EnableDhcp(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DhcpConfig)
		return ctx.Result(200, reply)
	}
}

func _DhcpService_DisableDhcp0_HTTP_Handler(srv DhcpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDhcpServiceDisableDhcp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DisableDhcp(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DhcpConfig)
		return ctx.Result(200, reply)
	}
}

func _DhcpService_ListLeases0_HTTP_Handler(srv DhcpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PageRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDhcpServiceListLeases)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLeases(ctx, req.(*PageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLeasesReply)
		return ctx.Result(200, reply)
	}
}

func _DhcpService_ListForeignServers0_HTTP_Handler(srv DhcpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PageRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDhcpServiceListForeignServers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListForeignServers(ctx, req.(*PageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListForeignServersReply)
		return ctx.Result(200, reply)
	}
}

type DhcpServiceHTTPClient interface {
	DisableDhcp(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *DhcpConfig, err error)
	EnableDhcp(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *DhcpConfig, err error)
	GetDhcpConfig(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *DhcpConfig, err error)
	ListForeignServers(ctx context.Context, req *PageRequest, opts ...http.CallOption) (rsp *ListForeignServersReply, err error)
	ListLeases(ctx context.Context, req *PageRequest, opts ...http.CallOption) (rsp *ListLeasesReply, err error)
	UpdateDhcpConfig(ctx context.Context, req *UpdateDhcpConfigRequest, opts ...http.CallOption) (rsp *DhcpConfig, err error)
}

type DhcpServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewDhcpServiceHTTPClient(client *http.Client) DhcpServiceHTTPClient {
	return &DhcpServiceHTTPClientImpl{client}
}

func (c *DhcpServiceHTTPClientImpl) DisableDhcp(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*DhcpConfig, error) {
	var out DhcpConfig
	pattern := "/api/v1/dhcp/disable"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDhcpServiceDisableDhcp))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DhcpServiceHTTPClientImpl) EnableDhcp(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*DhcpConfig, error) {
	var out DhcpConfig
	pattern := "/api/v1/dhcp/enable"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDhcpServiceEnableDhcp))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DhcpServiceHTTPClientImpl) GetDhcpConfig(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*DhcpConfig, error) {
	var out DhcpConfig
	pattern := "/api/v1/dhcp/config"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDhcpServiceGetDhcpConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DhcpServiceHTTPClientImpl) ListForeignServers(ctx context.Context, in *PageRequest, opts ...http.CallOption) (*ListForeignServersReply, error) {
	var out ListForeignServersReply
	pattern := "/api/v1/dhcp/conflicts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDhcpServiceListForeignServers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DhcpServiceHTTPClientImpl) ListLeases(ctx context.Context, in *PageRequest, opts ...http.CallOption) (*ListLeasesReply, error) {
	var out ListLeasesReply
	pattern := "/api/v1/dhcp/leases"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDhcpServiceListLeases))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DhcpServiceHTTPClientImpl) UpdateDhcpConfig(ctx context.Context, in *UpdateDhcpConfigRequest, opts ...http.CallOption) (*DhcpConfig, error) {
	var out DhcpConfig
	pattern := "/api/v1/dhcp/config"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDhcpServiceUpdateDhcpConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
