// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: netboot/v1/dhcp.proto

package netbootv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DhcpService_GetDhcpConfig_FullMethodName      = "/netboot.v1.DhcpService/GetDhcpConfig"
	DhcpService_UpdateDhcpConfig_FullMethodName   = "/netboot.v1.DhcpService/UpdateDhcpConfig"
	DhcpService_EnableDhcp_FullMethodName         = "/netboot.v1.DhcpService/EnableDhcp"
	DhcpService_DisableDhcp_FullMethodName        = "/netboot.v1.DhcpService/DisableDhcp"
	DhcpService_ListLeases_FullMethodName         = "/netboot.v1.DhcpService/ListLeases"
	DhcpService_ListForeignServers_FullMethodName = "/netboot.v1.DhcpService/ListForeignServers"
)

// DhcpServiceClient is the client API for DhcpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DhcpServiceClient interface {
	GetDhcpConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DhcpConfig, error)
	UpdateDhcpConfig(ctx context.Context, in *UpdateDhcpConfigRequest, opts ...grpc.CallOption) (*DhcpConfig, error)
	EnableDhcp(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DhcpConfig, error)
	DisableDhcp(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DhcpConfig, error)
	ListLeases(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ListLeasesReply, error)
	ListForeignServers(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ListForeignServersReply, error)
}

type dhcpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDhcpServiceClient(cc grpc.ClientConnInterface) DhcpServiceClient {
	return &dhcpServiceClient{cc}
}

func (c *dhcpServiceClient) GetDhcpConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DhcpConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DhcpConfig)
	err := c.cc.Invoke(ctx, DhcpService_GetDhcpConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dhcpServiceClient) UpdateDhcpConfig(ctx context.Context, in *UpdateDhcpConfigRequest, opts ...grpc.CallOption) (*DhcpConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DhcpConfig)
	err := c.cc.Invoke(ctx, DhcpService_UpdateDhcpConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dhcpServiceClient) EnableDhcp(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DhcpConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DhcpConfig)
	err := c.cc.Invoke(ctx, DhcpService_EnableDhcp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dhcpServiceClient) DisableDhcp(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DhcpConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DhcpConfig)
	err := c.cc.Invoke(ctx, DhcpService_DisableDhcp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dhcpServiceClient) ListLeases(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ListLeasesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLeasesReply)
	err := c.cc.Invoke(ctx, DhcpService_ListLeases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dhcpServiceClient) ListForeignServers(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ListForeignServersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListForeignServersReply)
	err := c.cc.Invoke(ctx, DhcpService_ListForeignServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DhcpServiceServer is the server API for DhcpService service.
// All implementations must embed UnimplementedDhcpServiceServer
// for forward compatibility.
type DhcpServiceServer interface {
	GetDhcpConfig(context.Context, *emptypb.Empty) (*DhcpConfig, error)
	UpdateDhcpConfig(context.Context, *UpdateDhcpConfigRequest) (*DhcpConfig, error)
	EnableDhcp(context.Context, *emptypb.Empty) (*DhcpConfig, error)
	DisableDhcp(context.Context, *emptypb.Empty) (*DhcpConfig, error)
	ListLeases(context.Context, *PageRequest) (*ListLeasesReply, error)
	ListForeignServers(context.Context, *PageRequest) (*ListForeignServersReply, error)
	mustEmbedUnimplementedDhcpServiceServer()
}

// UnimplementedDhcpServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDhcpServiceServer struct{}

func (UnimplementedDhcpServiceServer) GetDhcpConfig(context.Context, *emptypb.Empty) (*DhcpConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDhcpConfig not implemented")
}
func (UnimplementedDhcpServiceServer) UpdateDhcpConfig(context.Context, *UpdateDhcpConfigRequest) (*DhcpConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDhcpConfig not implemented")
}
func (UnimplementedDhcpServiceServer) EnableDhcp(context.Context, *emptypb.Empty) (*DhcpConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableDhcp not implemented")
}
func (UnimplementedDhcpServiceServer) DisableDhcp(context.Context, *emptypb.Empty) (*DhcpConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableDhcp not implemented")
}
func (UnimplementedDhcpServiceServer) ListLeases(context.Context, *PageRequest) (*ListLeasesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLeases not implemented")
}
func (UnimplementedDhcpServiceServer) ListForeignServers(context.Context, *PageRequest) (*ListForeignServersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListForeignServers not implemented")
}
func (UnimplementedDhcpServiceServer) mustEmbedUnimplementedDhcpServiceServer() {}
func (UnimplementedDhcpServiceServer) testEmbeddedByValue()                     {}

// UnsafeDhcpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DhcpServiceServer will
// result in compilation errors.
type UnsafeDhcpServiceServer interface {
	mustEmbedUnimplementedDhcpServiceServer()
}

func RegisterDhcpServiceServer(s grpc.ServiceRegistrar, srv DhcpServiceServer) {
	// If the following call pancis, it indicates UnimplementedDhcpServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DhcpService_ServiceDesc, srv)
}

func _DhcpService_GetDhcpConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DhcpServiceServer).GetDhcpConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DhcpService_GetDhcpConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DhcpServiceServer).GetDhcpConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DhcpService_UpdateDhcpConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDhcpConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DhcpServiceServer).UpdateDhcpConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DhcpService_UpdateDhcpConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DhcpServiceServer).UpdateDhcpConfig(ctx, req.(*UpdateDhcpConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DhcpService_EnableDhcp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DhcpServiceServer).EnableDhcp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DhcpService_EnableDhcp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DhcpServiceServer).EnableDhcp(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DhcpService_DisableDhcp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DhcpServiceServer).DisableDhcp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DhcpService_DisableDhcp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DhcpServiceServer).DisableDhcp(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DhcpService_ListLeases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DhcpServiceServer).ListLeases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DhcpService_ListLeases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DhcpServiceServer).ListLeases(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DhcpService_ListForeignServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DhcpServiceServer).ListForeignServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DhcpService_ListForeignServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DhcpServiceServer).ListForeignServers(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DhcpService_ServiceDesc is the grpc.ServiceDesc for DhcpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DhcpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netboot.v1.DhcpService",
	HandlerType: (*DhcpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDhcpConfig",
			Handler:    _DhcpService_GetDhcpConfig_Handler,
		},
		{
			MethodName: "UpdateDhcpConfig",
			Handler:    _DhcpService_UpdateDhcpConfig_Handler,
		},
		{
			MethodName: "EnableDhcp",
			Handler:    _DhcpService_EnableDhcp_Handler,
		},
		{
			MethodName: "DisableDhcp",
			Handler:    _DhcpService_DisableDhcp_Handler,
		},
		{
			MethodName: "ListLeases",
			Handler:    _DhcpService_ListLeases_Handler,
		},
		{
			MethodName: "ListForeignServers",
			Handler:    _DhcpService_ListForeignServers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "netboot/v1/dhcp.proto",
}
