// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: netboot/v1/machine.proto

package netbootv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMachineServiceCancelProvision = "/netboot.v1.MachineService/CancelProvision"
const OperationMachineServiceCreateMachine = "/netboot.v1.MachineService/CreateMachine"
const OperationMachineServiceDeleteMachine = "/netboot.v1.MachineService/DeleteMachine"
const OperationMachineServiceGetMachine = "/netboot.v1.MachineService/GetMachine"
const OperationMachineServiceListMachines = "/netboot.v1.MachineService/ListMachines"
const OperationMachineServiceListUnknownBoots = "/netboot.v1.MachineService/ListUnknownBoots"
const OperationMachineServiceProvision = "/netboot.v1.MachineService/Provision"
const OperationMachineServiceRegisterFromUnknown = "/netboot.v1.MachineService/RegisterFromUnknown"
const OperationMachineServiceUpdateMachine = "/netboot.v1.MachineService/UpdateMachine"

type MachineServiceHTTPServer interface {
	CancelProvision(context.Context, *GetMachineRequest) (*Machine, error)
	CreateMachine(context.Context, *CreateMachineRequest) (*Machine, error)
	DeleteMachine(context.Context, *GetMachineRequest) (*emptypb.Empty, error)
	GetMachine(context.Context, *GetMachineRequest) (*Machine, error)
	ListMachines(context.Context, *ListMachinesRequest) (*ListMachinesReply, error)
	ListUnknownBoots(context.Context, *PageRequest) (*ListUnknownBootsReply, error)
	Provision(context.Context, *GetMachineRequest) (*Machine, error)
	RegisterFromUnknown(context.Context, *RegisterFromUnknownRequest) (*Machine, error)
	UpdateMachine(context.Context, *UpdateMachineRequest) (*Machine, error)
}

func RegisterMachineServiceHTTPServer(s *http.Server, srv MachineServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/machines", _MachineService_ListMachines0_HTTP_Handler(srv))
	r.GET("/api/v1/machines/{id}", _MachineService_GetMachine0_HTTP_Handler(srv))
	r.POST("/api/v1/machines", _MachineService_CreateMachine0_HTTP_Handler(srv))
	r.PATCH("/api/v1/machines/{id}", _MachineService_UpdateMachine0_HTTP_Handler(srv))
	r.DELETE("/api/v1/machines/{id}", _MachineService_DeleteMachine0_HTTP_Handler(srv))
	r.POST("/api/v1/machines/{id}/provision", _MachineService_Provision0_HTTP_Handler(srv))
	r.POST("/api/v1/machines/{id}/cancel", _MachineService_CancelProvision0_HTTP_Handler(srv))
	r.GET("/api/v1/machines/unknown", _MachineService_ListUnknownBoots0_HTTP_Handler(srv))
	r.POST("/api/v1/machines/register-unknown", _MachineService_RegisterFromUnknown0_HTTP_Handler(srv))
}

func _MachineService_ListMachines0_HTTP_Handler(srv MachineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMachinesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMachineServiceListMachines)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMachines(ctx, req.(*ListMachinesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMachinesReply)
		return ctx.Result(200, reply)
	}
}

func _MachineService_GetMachine0_HTTP_Handler(srv MachineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMachineRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMachineServiceGetMachine)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMachine(ctx, req.(*GetMachineRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Machine)
		return ctx.Result(200, reply)
	}
}

func _MachineService_CreateMachine0_HTTP_Handler(srv MachineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateMachineRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMachineServiceCreateMachine)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateMachine(ctx, req.(*CreateMachineRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Machine)
		return ctx.Result(200, reply)
	}
}

func _MachineService_UpdateMachine0_HTTP_Handler(srv MachineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateMachineRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMachineServiceUpdateMachine)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateMachine(ctx, req.(*UpdateMachineRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Machine)
		return ctx.Result(200, reply)
	}
}

func _MachineService_DeleteMachine0_HTTP_Handler(srv MachineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMachineRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMachineServiceDeleteMachine)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteMachine(ctx, req.(*GetMachineRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _MachineService_Provision0_HTTP_Handler(srv MachineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMachineRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMachineServiceProvision)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Provision(ctx, req.(*GetMachineRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Machine)
		return ctx.Result(200, reply)
	}
}

func _MachineService_CancelProvision0_HTTP_Handler(srv MachineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMachineRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMachineServiceCancelProvision)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelProvision(ctx, req.(*GetMachineRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Machine)
		return ctx.Result(200, reply)
	}
}

func _MachineService_ListUnknownBoots0_HTTP_Handler(srv MachineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PageRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMachineServiceListUnknownBoots)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListUnknownBoots(ctx, req.(*PageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListUnknownBootsReply)
		return ctx.Result(200, reply)
	}
}

func _MachineService_RegisterFromUnknown0_HTTP_Handler(srv MachineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegisterFromUnknownRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMachineServiceRegisterFromUnknown)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegisterFromUnknown(ctx, req.(*RegisterFromUnknownRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Machine)
		return ctx.Result(200, reply)
	}
}

type MachineServiceHTTPClient interface {
	CancelProvision(ctx context.Context, req *GetMachineRequest, opts ...http.CallOption) (rsp *Machine, err error)
	CreateMachine(ctx context.Context, req *CreateMachineRequest, opts ...http.CallOption) (rsp *Machine, err error)
	DeleteMachine(ctx context.Context, req *GetMachineRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetMachine(ctx context.Context, req *GetMachineRequest, opts ...http.CallOption) (rsp *Machine, err error)
	ListMachines(ctx context.Context, req *ListMachinesRequest, opts ...http.CallOption) (rsp *ListMachinesReply, err error)
	ListUnknownBoots(ctx context.Context, req *PageRequest, opts ...http.CallOption) (rsp *ListUnknownBootsReply, err error)
	Provision(ctx context.Context, req *GetMachineRequest, opts ...http.CallOption) (rsp *Machine, err error)
	RegisterFromUnknown(ctx context.Context, req *RegisterFromUnknownRequest, opts ...http.CallOption) (rsp *Machine, err error)
	UpdateMachine(ctx context.Context, req *UpdateMachineRequest, opts ...http.CallOption) (rsp *Machine, err error)
}

type MachineServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMachineServiceHTTPClient(client *http.Client) MachineServiceHTTPClient {
	return &MachineServiceHTTPClientImpl{client}
}

func (c *MachineServiceHTTPClientImpl) CancelProvision(ctx context.Context, in *GetMachineRequest, opts ...http.CallOption) (*Machine, error) {
	var out Machine
	pattern := "/api/v1/machines/{id}/cancel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMachineServiceCancelProvision))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MachineServiceHTTPClientImpl) CreateMachine(ctx context.Context, in *CreateMachineRequest, opts ...http.CallOption) (*Machine, error) {
	var out Machine
	pattern := "/api/v1/machines"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMachineServiceCreateMachine))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MachineServiceHTTPClientImpl) DeleteMachine(ctx context.Context, in *GetMachineRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/machines/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMachineServiceDeleteMachine))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MachineServiceHTTPClientImpl) GetMachine(ctx context.Context, in *GetMachineRequest, opts ...http.CallOption) (*Machine, error) {
	var out Machine
	pattern := "/api/v1/machines/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMachineServiceGetMachine))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MachineServiceHTTPClientImpl) ListMachines(ctx context.Context, in *ListMachinesRequest, opts ...http.CallOption) (*ListMachinesReply, error) {
	var out ListMachinesReply
	pattern := "/api/v1/machines"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMachineServiceListMachines))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MachineServiceHTTPClientImpl) ListUnknownBoots(ctx context.Context, in *PageRequest, opts ...http.CallOption) (*ListUnknownBootsReply, error) {
	var out ListUnknownBootsReply
	pattern := "/api/v1/machines/unknown"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMachineServiceListUnknownBoots))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MachineServiceHTTPClientImpl) Provision(ctx context.Context, in *GetMachineRequest, opts ...http.CallOption) (*Machine, error) {
	var out Machine
	pattern := "/api/v1/machines/{id}/provision"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMachineServiceProvision))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MachineServiceHTTPClientImpl) RegisterFromUnknown(ctx context.Context, in *RegisterFromUnknownRequest, opts ...http.CallOption) (*Machine, error) {
	var out Machine
	pattern := "/api/v1/machines/register-unknown"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMachineServiceRegisterFromUnknown))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MachineServiceHTTPClientImpl) UpdateMachine(ctx context.Context, in *UpdateMachineRequest, opts ...http.CallOption) (*Machine, error) {
	var out Machine
	pattern := "/api/v1/machines/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMachineServiceUpdateMachine))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
