// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: netboot/v1/profile.proto

package netbootv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProfileServiceCloneProfile = "/netboot.v1.ProfileService/CloneProfile"
const OperationProfileServiceCreateProfile = "/netboot.v1.ProfileService/CreateProfile"
const OperationProfileServiceDeleteProfile = "/netboot.v1.ProfileService/DeleteProfile"
const OperationProfileServiceGetProfile = "/netboot.v1.ProfileService/GetProfile"
const OperationProfileServiceListProfiles = "/netboot.v1.ProfileService/ListProfiles"
const OperationProfileServicePreviewProfile = "/netboot.v1.ProfileService/PreviewProfile"
const OperationProfileServiceUpdateProfile = "/netboot.v1.ProfileService/UpdateProfile"

type ProfileServiceHTTPServer interface {
	CloneProfile(context.Context, *CloneProfileRequest) (*Profile, error)
	CreateProfile(context.Context, *ProfileInput) (*Profile, error)
	DeleteProfile(context.Context, *GetProfileRequest) (*emptypb.Empty, error)
	GetProfile(context.Context, *GetProfileRequest) (*Profile, error)
	ListProfiles(context.Context, *PageRequest) (*ListProfilesReply, error)
	PreviewProfile(context.Context, *PreviewProfileRequest) (*PreviewProfileReply, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*Profile, error)
}

func RegisterProfileServiceHTTPServer(s *http.Server, srv ProfileServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/profiles", _ProfileService_ListProfiles0_HTTP_Handler(srv))
	r.GET("/api/v1/profiles/{id}", _ProfileService_GetProfile0_HTTP_Handler(srv))
	r.POST("/api/v1/profiles", _ProfileService_CreateProfile0_HTTP_Handler(srv))
	r.PUT("/api/v1/profiles/{id}", _ProfileService_UpdateProfile0_HTTP_Handler(srv))
	r.POST("/api/v1/profiles/{id}/clone", _ProfileService_CloneProfile0_HTTP_Handler(srv))
	r.DELETE("/api/v1/profiles/{id}", _ProfileService_DeleteProfile0_HTTP_Handler(srv))
	r.POST("/api/v1/profiles/{id}/preview", _ProfileService_PreviewProfile0_HTTP_Handler(srv))
}

func _ProfileService_ListProfiles0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PageRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceListProfiles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProfiles(ctx, req.(*PageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProfilesReply)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_GetProfile0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProfileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceGetProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProfile(ctx, req.(*GetProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Profile)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_CreateProfile0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProfileInput
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceCreateProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProfile(ctx, req.(*ProfileInput))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Profile)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_UpdateProfile0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceUpdateProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProfile(ctx, req.(*UpdateProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Profile)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_CloneProfile0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CloneProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceCloneProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CloneProfile(ctx, req.(*CloneProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Profile)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_DeleteProfile0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProfileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceDeleteProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteProfile(ctx, req.(*GetProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_PreviewProfile0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PreviewProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServicePreviewProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PreviewProfile(ctx, req.(*PreviewProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PreviewProfileReply)
		return ctx.Result(200, reply)
	}
}

type ProfileServiceHTTPClient interface {
	CloneProfile(ctx context.Context, req *CloneProfileRequest, opts ...http.CallOption) (rsp *Profile, err error)
	CreateProfile(ctx context.Context, req *ProfileInput, opts ...http.CallOption) (rsp *Profile, err error)
	DeleteProfile(ctx context.Context, req *GetProfileRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetProfile(ctx context.Context, req *GetProfileRequest, opts ...http.CallOption) (rsp *Profile, err error)
	ListProfiles(ctx context.Context, req *PageRequest, opts ...http.CallOption) (rsp *ListProfilesReply, err error)
	PreviewProfile(ctx context.Context, req *PreviewProfileRequest, opts ...http.CallOption) (rsp *PreviewProfileReply, err error)
	UpdateProfile(ctx context.Context, req *UpdateProfileRequest, opts ...http.CallOption) (rsp *Profile, err error)
}

type ProfileServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewProfileServiceHTTPClient(client *http.Client) ProfileServiceHTTPClient {
	return &ProfileServiceHTTPClientImpl{client}
}

func (c *ProfileServiceHTTPClientImpl) CloneProfile(ctx context.Context, in *CloneProfileRequest, opts ...http.CallOption) (*Profile, error) {
	var out Profile
	pattern := "/api/v1/profiles/{id}/clone"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceCloneProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) CreateProfile(ctx context.Context, in *ProfileInput, opts ...http.CallOption) (*Profile, error) {
	var out Profile
	pattern := "/api/v1/profiles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceCreateProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) DeleteProfile(ctx context.Context, in *GetProfileRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/profiles/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileServiceDeleteProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...http.CallOption) (*Profile, error) {
	var out Profile
	pattern := "/api/v1/profiles/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileServiceGetProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) ListProfiles(ctx context.Context, in *PageRequest, opts ...http.CallOption) (*ListProfilesReply, error) {
	var out ListProfilesReply
	pattern := "/api/v1/profiles"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileServiceListProfiles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) PreviewProfile(ctx context.Context, in *PreviewProfileRequest, opts ...http.CallOption) (*PreviewProfileReply, error) {
	var out PreviewProfileReply
	pattern := "/api/v1/profiles/{id}/preview"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServicePreviewProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...http.CallOption) (*Profile, error) {
	var out Profile
	pattern := "/api/v1/profiles/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileServiceUpdateProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
