// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: netboot/v1/session.proto

package netbootv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSessionServiceGetSession = "/netboot.v1.SessionService/GetSession"
const OperationSessionServiceListSessions = "/netboot.v1.SessionService/ListSessions"

type SessionServiceHTTPServer interface {
	GetSession(context.Context, *GetSessionRequest) (*SessionDetail, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsReply, error)
}

func RegisterSessionServiceHTTPServer(s *http.Server, srv SessionServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/sessions", _SessionService_ListSessions0_HTTP_Handler(srv))
	r.GET("/api/v1/sessions/{id}", _SessionService_GetSession0_HTTP_Handler(srv))
}

func _SessionService_ListSessions0_HTTP_Handler(srv SessionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSessionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSessionServiceListSessions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSessions(ctx, req.(*ListSessionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSessionsReply)
		return ctx.Result(200, reply)
	}
}

func _SessionService_GetSession0_HTTP_Handler(srv SessionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSessionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSessionServiceGetSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSession(ctx, req.(*GetSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SessionDetail)
		return ctx.Result(200, reply)
	}
}

type SessionServiceHTTPClient interface {
	GetSession(ctx context.Context, req *GetSessionRequest, opts ...http.CallOption) (rsp *SessionDetail, err error)
	ListSessions(ctx context.Context, req *ListSessionsRequest, opts ...http.CallOption) (rsp *ListSessionsReply, err error)
}

type SessionServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSessionServiceHTTPClient(client *http.Client) SessionServiceHTTPClient {
	return &SessionServiceHTTPClientImpl{client}
}

func (c *SessionServiceHTTPClientImpl) GetSession(ctx context.Context, in *GetSessionRequest, opts ...http.CallOption) (*SessionDetail, error) {
	var out SessionDetail
	pattern := "/api/v1/sessions/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSessionServiceGetSession))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SessionServiceHTTPClientImpl) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...http.CallOption) (*ListSessionsReply, error) {
	var out ListSessionsReply
	pattern := "/api/v1/sessions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSessionServiceListSessions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
